# Generated by Django 4.1.5 on 2023-01-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('lnurl', models.CharField(max_length=500)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
