# Generated by Django 4.1.5 on 2023-01-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wallet_payment_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='lnurl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
