# Generated by Django 4.1.5 on 2023-01-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_payment_lnurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='management_code',
            field=models.CharField(blank=True, default='Test', max_length=50, null=True),
        ),
    ]
