# Generated by Django 4.1.5 on 2023-01-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_payment_management_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='management_code',
            field=models.CharField(blank=True, default='7UHxKd', max_length=50, null=True, unique=True),
        ),
    ]
