# Generated by Django 4.1.5 on 2023-01-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_payment_management_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pub_key',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='management_code',
            field=models.CharField(blank=True, default='KYJXCW', max_length=50, null=True),
        ),
    ]
