# Generated by Django 4.1.5 on 2023-01-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_payment_management_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='nip05user',
            name='hex_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='management_code',
            field=models.CharField(blank=True, default='Q5KUZr', max_length=50, null=True),
        ),
    ]
