# Generated by Django 4.1.5 on 2023-01-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_backcard_alter_payment_management_code_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='back_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.backcard'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='management_code',
            field=models.CharField(blank=True, default='hDz9B5', max_length=50, null=True),
        ),
    ]
