# Generated by Django 4.1.5 on 2023-01-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_card_back_card_alter_payment_management_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backcard',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='back_cards'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='management_code',
            field=models.CharField(blank=True, default='2pDJqE', max_length=50, null=True),
        ),
    ]
