# Generated by Django 4.1.5 on 2023-01-16 11:58

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('main', '0015_alter_backcard_image_alter_payment_management_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='nip05user',
            name='cards',
            field=models.ManyToManyField(blank=True, to='main.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='management_code',
            field=models.CharField(blank=True, default='uhHP7D', max_length=50, null=True),
        ),
    ]
