# Generated by Django 4.1.5 on 2023-01-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_nip05user_cards_alter_card_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='management_code',
            field=models.CharField(blank=True, default='c7XExz', max_length=50, null=True),
        ),
    ]
